### PR TITLE
Add stretchy bone IK component

### PR DESCRIPTION
**Pull request by BigRoy**
- Includes midpoint pinning
- Includes IK/FK blending
- Includes midpoint sliding
- Includes soft IK (both stretchy and non-stretchy)

### CODE REVIEW

**Comment by BigRoy** [comment]
Also discussed on [Fabric Engine forums](http://forums.fabricengine.com/discussion/232/twoboneiksolver-stretchy-and-soft-ik#latest)

**Comment by EricTRocks** [comment]
Thanks @BigRoy and many thanks for updating with a component too!

**Comment by BigRoy** [comment]
@EricTRocks and of course, no problem! glad to contribute.

**Comment by EricTRocks** [comment]
Hey @BigRoy I check this out tonight. Great work! I would say that scaling would not be the best approach. If you have other objects attached to the outputs that are scaling it'll get a bit screwy with the other components. I think having it translate instead would be a better approach. 

Another thing I noticed was that if you turn on drawDebug it stops working. Can you look into that?

**Comment by BigRoy** [comment]
> If you have other objects attached to the outputs that are scaling it'll get a bit screwy with the other components. I think having it translate instead would be a better approach.

Sure. I'll fix that up.

> Another thing I noticed was that if you turn on drawDebug it stops working. Can you look into that?

This didn't happen to me. 
Did you enable it on the guide or the rig? 
For testing, did you `pull` this into your repo with the latest code base, or did you `checkout` mine?

**Comment by EricTRocks** [comment]
I pulled your changes into a new branch based off the latest develop2.X

**Comment by BigRoy** [comment]
Cool. Will try to find some weekend to do the same and debug the behavior under those conditions. Thanks!

**Comment by BigRoy** [comment]
Wow.. that took some time. Finally found some time to have another play with is. Turns out the drawDebug issue was very trivial to fix.

I also remove the scaling when the IK stretches (the scaling of the Xfo itself). Somehow I'm not getting the bones to be drawn larger even if the boneLen passed in changes. Is that initialized once and not updated afterwards?

**Comment by EricTRocks** [comment]
Yes using the normal draw bone methods it doesn't update the debug drawing shape length. I believe this can be done with not so much work. I'll pull this and test again and should be able to merge into the dev2 branch shortly.

**Comment by EricTRocks** [comment]
I think there needs to be minimums set for the bone  lengths params. Setting either to 0 makes the xfos / bones disappear.

If you could, I would test if the root and ik target are at the same position in IK mode.  If they are you should set the xfo for the bone 0 to aim at the up vector and the bone 1 to aim from the end of bone 0 back to the ik target. Currently the bones / transforms completely disappear.

**Comment by BigRoy** [comment]
Sure no problem. Hope I can find some more time tonight to have a look so we can get this in!

Preferably I also make it work with the foot component. Is there something special I need to do to make that work? (It's that back and forth connection, right?)

**Comment by EricTRocks** [comment]
Take a peak at the leg component's inputs / outputs. Instead of using the IK control for the IK solver target you'll use the ikTarget input from the foot. You'll also need an output of the IK control too that the foot uses.

**Comment by BigRoy** [comment]
Ended up clamping the minimum length to a small value so it would work in any situation, what you think?

**Comment by EricTRocks** [comment]
yes that should work. :)

**Pull request merged**
