### PR TITLE
Allow for default values in kl operators

### PR DESCRIPTION
**Pull request by todderasesareddot**
Allow for default values in kl operators.  
See issue  https://github.com/fabric-engine/Kraken/issues/78

UPDATE:

Default values for Kraken KL Operators are now stored in a struct associated with the solver object.

Using a dictionary with generic RTVal type may work, but we need to actually get the simple type for these values when we set the attributes of the DCC.  The only thing that could be simpler is if there was a function to test if the RTVal object had a named attribute. Right now, I'm getthing that info through the JSON description.  It works fine, but could be simpler if there was just a simple call.

See the updated solvers "TentacleSolver" and "RigScaleSolver" in this branch for reference how it works.

Example:
struct RigScaleSolverDefaults : KrakenSolverDefaults { 
  Mat44 target;
};
// Default Constructor
function RigScaleSolverDefaults()
{
  this.target = Mat44();
}

object RigScaleSolver : KrakenSolver {
  RigScaleSolverDefaults defaults;
};

### CODE REVIEW

**Comment by EricTRocks** [comment]
I don't think having Python code in KL is a good idea. Instead we should have default value args that are of KL types that we can convert to Python types via RTVals as needed. The default values don't need to be converted to Python types as they are going to be converted to RTVals and set back on the op anyway right?

My concern is that people will be confused as to why any Python code (even in double quotes) is in a .kl file. Also we have the mechanisms in the Fabric API to do the conversion.

**Comment by EricTRocks** [comment]
Yes I think adding a dictionary of key / value pairs would be best as it will be a single structure that stores the default values instead of just a bunch of attributes hanging onto the main object.

**Comment by todderasesareddot** [comment]
Hmmm...you don't mean a dictionary, right?  Just a kl struct or object to hold the RTVals?

To me, just giving the operator object attributes that match the argument names is nice and simple and easily accessible without needing to create more structs, etc.

**Comment by EricTRocks** [comment]
No I mean a KL dictionary. See [KL Dictionaries](http://docs.fabric-engine.com/FabricEngine/2.2.0/HTML/KLProgrammingGuide/types.html#dictionaries)

The KrakenSolver object can have a `default_values` attribute that is a dictionary with keys that match. If we store in a single place rather than flat list on the operator object, it means we can access the default values easier without much extra work.

Sort of like how I've been adding the `self.default_values` attribute to guide components. Eventually I want to be able to reset component values to defaults. Since I have all the default values stored in 1 place that is the `self.default_values` dictionary, I don't have to iterate over all attributes to find all the default value ones and won't have to do any string operations like splitting or appending to construct the default attribute name.

**Comment by todderasesareddot** [comment]
I didn't even know KL had dictionaries!  But there is Helge's friendly face telling me all about them....
https://player.vimeo.com/video/79812070

But they are strongly typed to a single type, no?  I already implemented this using an object which works quite well.  Let me know if I'm missing something about dictionaries.

**Comment by EricTRocks** [comment]
Yes you're correct. I didn't think they were typed.

**Comment by todderasesareddot** [comment]
I'll update this PR with a new version for you to look at.

**Comment by EricTRocks** [comment]
Example of how to create an RTVal dict allowing for dynamic value types. Adding the `RTVal defaultValues[String]` as a member of the KrakenSolver object would be the first step.

`
operator entry(){
  RTVal defaultValues[String];

  defaultValues['myArg1'] = 1;
  defaultValues['myArg2'] = "stringValue";

  report(defaultValues['myArg1']);

}
`

**Comment by EricTRocks** [comment]
OK after further discussion with Peter and other Fabric folks, it seems that returning RTVals and using them to set onto the Canvas ops directly will work so the RTVal dictionary will be a valid workflow. There was a suggestion to also create methods on the DefaultValues struct for returning the arguments and asserting that they are of the correct type.

`defaultValStruct.getBooleanValue(String valueKey)`
`defaultValStruct.getMat44Value(String valueKey)`
etc...

**Comment by todderasesareddot** [comment]
I committed new changes and updated the PR description.

Default settings are stored as a struct associated with the solver object.  We could possibly switch to a dictionary using generic RTVal types, but I don't see the benefit since I rely on the RTVal to be converted to a simpleType in some cases.

This should be backwards compatible to current KL solvers.  Tried to do decent logging/debugging so users know when they are missing a default value or are using one.

Now, authors can create solvers without needing to connect or set all inputs/outputs which can be a real pain when starting to write a component.  Also, this protects components if someone adds an optional attribute to a solver.  It will still work.

**Comment by EricTRocks** [comment]
Closing as this has been refactored on another branch that will have a pull request opened for it.

**Pull request closed without merging**
